// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: remote_command.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "remote_command.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace network_io {

namespace {

const ::google::protobuf::Descriptor* Request_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Request_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Request_Type_descriptor_ = NULL;
const ::google::protobuf::EnumDescriptor* Request_Code_descriptor_ = NULL;
const ::google::protobuf::Descriptor* FileInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FileInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* Response_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Response_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Response_ReturnCode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_remote_5fcommand_2eproto() {
  protobuf_AddDesc_remote_5fcommand_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "remote_command.proto");
  GOOGLE_CHECK(file != NULL);
  Request_descriptor_ = file->message_type(0);
  static const int Request_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, securitytoken_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, intextra_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, stringextra_),
  };
  Request_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Request_descriptor_,
      Request::default_instance_,
      Request_offsets_,
      -1,
      -1,
      -1,
      sizeof(Request),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Request, _is_default_instance_));
  Request_Type_descriptor_ = Request_descriptor_->enum_type(0);
  Request_Code_descriptor_ = Request_descriptor_->enum_type(1);
  FileInfo_descriptor_ = file->message_type(1);
  static const int FileInfo_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FileInfo, absolutefilepath_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FileInfo, filename_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FileInfo, isdirectory_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FileInfo, size_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FileInfo, child_),
  };
  FileInfo_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      FileInfo_descriptor_,
      FileInfo::default_instance_,
      FileInfo_offsets_,
      -1,
      -1,
      -1,
      sizeof(FileInfo),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FileInfo, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FileInfo, _is_default_instance_));
  Response_descriptor_ = file->message_type(2);
  static const int Response_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, requesttype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, requestcode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, returncode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, intvalue_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, file_),
  };
  Response_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Response_descriptor_,
      Response::default_instance_,
      Response_offsets_,
      -1,
      -1,
      -1,
      sizeof(Response),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Response, _is_default_instance_));
  Response_ReturnCode_descriptor_ = Response_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_remote_5fcommand_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Request_descriptor_, &Request::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      FileInfo_descriptor_, &FileInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Response_descriptor_, &Response::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_remote_5fcommand_2eproto() {
  delete Request::default_instance_;
  delete Request_reflection_;
  delete FileInfo::default_instance_;
  delete FileInfo_reflection_;
  delete Response::default_instance_;
  delete Response_reflection_;
}

void protobuf_AddDesc_remote_5fcommand_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024remote_command.proto\022\nnetwork_io\"\375\020\n\007R"
    "equest\022&\n\004type\030\001 \001(\0162\030.network_io.Reques"
    "t.Type\022&\n\004code\030\002 \001(\0162\030.network_io.Reques"
    "t.Code\022\025\n\rsecurityToken\030\003 \001(\t\022\020\n\010intExtr"
    "a\030\004 \001(\005\022\023\n\013stringExtra\030\005 \001(\t\"K\n\004Type\022\n\n\006"
    "SIMPLE\020\000\022\014\n\010EXPLORER\020\001\022\014\n\010KEYBOARD\020\002\022\006\n\002"
    "AI\020\003\022\n\n\006VOLUME\020\004\022\007\n\003APP\020\005\"\226\017\n\004Code\022\010\n\004NO"
    "NE\020\000\022\n\n\006DEFINE\020\001\022\n\n\006STATUS\020\002\022\006\n\002ON\020\003\022\007\n\003"
    "OFF\020\004\022\010\n\004PING\020\005\022\010\n\004TEST\020\006\022\017\n\013KILL_SERVER"
    "\020\007\022\014\n\010SHUTDOWN\020\010\022\021\n\rSWITCH_WINDOW\020\t\022\010\n\004L"
    "OCK\020\n\022\010\n\004MUTE\020\013\022\007\n\003SAY\020\014\022\013\n\007DPAD_UP\020\r\022\r\n"
    "\tDPAD_DOWN\020\016\022\r\n\tDPAD_LEFT\020\017\022\016\n\nDPAD_RIGH"
    "T\020\020\022\024\n\020MEDIA_PLAY_PAUSE\020\024\022\016\n\nMEDIA_STOP\020"
    "\025\022\022\n\016MEDIA_PREVIOUS\020\026\022\016\n\nMEDIA_NEXT\020\027\022\014\n"
    "\010MEDIA_FF\020\030\022\020\n\014MEDIA_REWIND\020\031\022\017\n\013QUERY_R"
    "OOTS\020\032\022\022\n\016QUERY_CHILDREN\020\033\022\024\n\020OPEN_SERVE"
    "R_SIDE\020\034\022\024\n\020OPEN_CLIENT_SIDE\020\035\022\020\n\014KEYCOD"
    "E_CTRL\020\036\022\021\n\rKEYCODE_SHIFT\020\037\022\024\n\020KEYCODE_A"
    "LT_LEFT\020 \022\025\n\021KEYCODE_ALT_RIGHT\020!\022\023\n\017KEYC"
    "ODE_WINDOWS\020\"\022\021\n\rKEYCODE_ENTER\020(\022\022\n\016KEYC"
    "ODE_ESCAPE\020)\022\022\n\016KEYCODE_DELETE\020*\022\021\n\rKEYC"
    "ODE_SPACE\020+\022\025\n\021KEYCODE_BACKSPACE\020,\022\017\n\013KE"
    "YCODE_TAB\020-\022\016\n\tKEYCODE_0\020\364\003\022\016\n\tKEYCODE_1"
    "\020\365\003\022\016\n\tKEYCODE_2\020\366\003\022\016\n\tKEYCODE_3\020\367\003\022\016\n\tK"
    "EYCODE_4\020\370\003\022\016\n\tKEYCODE_5\020\371\003\022\016\n\tKEYCODE_6"
    "\020\372\003\022\016\n\tKEYCODE_7\020\373\003\022\016\n\tKEYCODE_8\020\374\003\022\016\n\tK"
    "EYCODE_9\020\375\003\022\016\n\tKEYCODE_A\020\376\003\022\016\n\tKEYCODE_B"
    "\020\377\003\022\016\n\tKEYCODE_C\020\200\004\022\016\n\tKEYCODE_D\020\201\004\022\016\n\tK"
    "EYCODE_E\020\202\004\022\016\n\tKEYCODE_F\020\203\004\022\016\n\tKEYCODE_G"
    "\020\204\004\022\016\n\tKEYCODE_H\020\205\004\022\016\n\tKEYCODE_I\020\206\004\022\016\n\tK"
    "EYCODE_J\020\207\004\022\016\n\tKEYCODE_K\020\210\004\022\016\n\tKEYCODE_L"
    "\020\211\004\022\016\n\tKEYCODE_M\020\212\004\022\016\n\tKEYCODE_N\020\213\004\022\016\n\tK"
    "EYCODE_O\020\214\004\022\016\n\tKEYCODE_P\020\215\004\022\016\n\tKEYCODE_Q"
    "\020\216\004\022\016\n\tKEYCODE_R\020\217\004\022\016\n\tKEYCODE_S\020\220\004\022\016\n\tK"
    "EYCODE_T\020\221\004\022\016\n\tKEYCODE_U\020\222\004\022\016\n\tKEYCODE_V"
    "\020\223\004\022\016\n\tKEYCODE_W\020\224\004\022\016\n\tKEYCODE_X\020\225\004\022\016\n\tK"
    "EYCODE_Y\020\226\004\022\016\n\tKEYCODE_Z\020\227\004\022\017\n\nKEYCODE_F"
    "1\020\246\004\022\017\n\nKEYCODE_F2\020\247\004\022\017\n\nKEYCODE_F3\020\250\004\022\017"
    "\n\nKEYCODE_F4\020\251\004\022\017\n\nKEYCODE_F5\020\252\004\022\017\n\nKEYC"
    "ODE_F6\020\253\004\022\017\n\nKEYCODE_F7\020\254\004\022\017\n\nKEYCODE_F8"
    "\020\255\004\022\017\n\nKEYCODE_F9\020\256\004\022\020\n\013KEYCODE_F10\020\257\004\022\020"
    "\n\013KEYCODE_F11\020\260\004\022\020\n\013KEYCODE_F12\020\261\004\022\023\n\016KE"
    "YCODE_EQUALS\020\330\004\022\022\n\rKEYCODE_MINUS\020\331\004\022\021\n\014K"
    "EYCODE_PLUS\020\332\004\022\021\n\014KEYCODE_STAR\020\333\004\022\022\n\rKEY"
    "CODE_SLASH\020\334\004\022\026\n\021KEYCODE_BACKSLASH\020\335\004\022\027\n"
    "\022KEYCODE_UNDERSCORE\020\336\004\022\021\n\014KEYCODE_PIPE\020\337"
    "\004\022\022\n\rKEYCODE_COMMA\020\340\004\022\024\n\017KEYCODE_PERIODE"
    "\020\341\004\022\022\n\rKEYCODE_COLON\020\342\004\022\026\n\021KEYCODE_SEMIC"
    "OLON\020\343\004\022\017\n\nKEYCODE_AT\020\344\004\022\027\n\022KEYCODE_APOS"
    "TROPHE\020\345\004\022\027\n\022KEYCODE_LEFT_PAREN\020\212\005\022\031\n\024KE"
    "YCODE_RIGHT_PARENT\020\213\005\022\031\n\024KEYCODE_LEFT_BR"
    "ACKET\020\214\005\022\032\n\025KEYCODE_RIGHT_BRACKET\020\215\005\022\037\n\032"
    "KEYCODE_LEFT_CURLY_BRACKET\020\216\005\022 \n\033KEYCODE"
    "_RIGHT_CURLY_BRACKET\020\217\005\022\037\n\032KEYCODE_LEFT_"
    "ANGLE_BRACKET\020\220\005\022 \n\033KEYCODE_RIGHT_ANGLE_"
    "BRACKET\020\221\005\"~\n\010FileInfo\022\030\n\020absoluteFilePa"
    "th\030\001 \001(\t\022\020\n\010filename\030\002 \001(\t\022\023\n\013isDirector"
    "y\030\003 \001(\010\022\014\n\004size\030\004 \001(\r\022#\n\005child\030\005 \001(\0132\024.n"
    "etwork_io.FileInfo\"\220\002\n\010Response\022-\n\013reque"
    "stType\030\001 \001(\0162\030.network_io.Request.Type\022-"
    "\n\013requestCode\030\002 \001(\0162\030.network_io.Request"
    ".Code\0223\n\nreturnCode\030\003 \001(\0162\037.network_io.R"
    "esponse.ReturnCode\022\017\n\007message\030\004 \001(\t\022\020\n\010i"
    "ntValue\030\005 \001(\005\022\"\n\004file\030\006 \001(\0132\024.network_io"
    ".FileInfo\"*\n\nReturnCode\022\016\n\nRC_SUCCESS\020\000\022"
    "\014\n\010RC_ERROR\020\001B0\n\037org.es.uremote.request."
    "protobufB\rRemoteCommandb\006proto3", 2671);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "remote_command.proto", &protobuf_RegisterTypes);
  Request::default_instance_ = new Request();
  FileInfo::default_instance_ = new FileInfo();
  Response::default_instance_ = new Response();
  Request::default_instance_->InitAsDefaultInstance();
  FileInfo::default_instance_->InitAsDefaultInstance();
  Response::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_remote_5fcommand_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_remote_5fcommand_2eproto {
  StaticDescriptorInitializer_remote_5fcommand_2eproto() {
    protobuf_AddDesc_remote_5fcommand_2eproto();
  }
} static_descriptor_initializer_remote_5fcommand_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

const ::google::protobuf::EnumDescriptor* Request_Type_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Request_Type_descriptor_;
}
bool Request_Type_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Request_Type Request::SIMPLE;
const Request_Type Request::EXPLORER;
const Request_Type Request::KEYBOARD;
const Request_Type Request::AI;
const Request_Type Request::VOLUME;
const Request_Type Request::APP;
const Request_Type Request::Type_MIN;
const Request_Type Request::Type_MAX;
const int Request::Type_ARRAYSIZE;
#endif  // _MSC_VER
const ::google::protobuf::EnumDescriptor* Request_Code_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Request_Code_descriptor_;
}
bool Request_Code_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 40:
    case 41:
    case 42:
    case 43:
    case 44:
    case 45:
    case 500:
    case 501:
    case 502:
    case 503:
    case 504:
    case 505:
    case 506:
    case 507:
    case 508:
    case 509:
    case 510:
    case 511:
    case 512:
    case 513:
    case 514:
    case 515:
    case 516:
    case 517:
    case 518:
    case 519:
    case 520:
    case 521:
    case 522:
    case 523:
    case 524:
    case 525:
    case 526:
    case 527:
    case 528:
    case 529:
    case 530:
    case 531:
    case 532:
    case 533:
    case 534:
    case 535:
    case 550:
    case 551:
    case 552:
    case 553:
    case 554:
    case 555:
    case 556:
    case 557:
    case 558:
    case 559:
    case 560:
    case 561:
    case 600:
    case 601:
    case 602:
    case 603:
    case 604:
    case 605:
    case 606:
    case 607:
    case 608:
    case 609:
    case 610:
    case 611:
    case 612:
    case 613:
    case 650:
    case 651:
    case 652:
    case 653:
    case 654:
    case 655:
    case 656:
    case 657:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Request_Code Request::NONE;
const Request_Code Request::DEFINE;
const Request_Code Request::STATUS;
const Request_Code Request::ON;
const Request_Code Request::OFF;
const Request_Code Request::PING;
const Request_Code Request::TEST;
const Request_Code Request::KILL_SERVER;
const Request_Code Request::SHUTDOWN;
const Request_Code Request::SWITCH_WINDOW;
const Request_Code Request::LOCK;
const Request_Code Request::MUTE;
const Request_Code Request::SAY;
const Request_Code Request::DPAD_UP;
const Request_Code Request::DPAD_DOWN;
const Request_Code Request::DPAD_LEFT;
const Request_Code Request::DPAD_RIGHT;
const Request_Code Request::MEDIA_PLAY_PAUSE;
const Request_Code Request::MEDIA_STOP;
const Request_Code Request::MEDIA_PREVIOUS;
const Request_Code Request::MEDIA_NEXT;
const Request_Code Request::MEDIA_FF;
const Request_Code Request::MEDIA_REWIND;
const Request_Code Request::QUERY_ROOTS;
const Request_Code Request::QUERY_CHILDREN;
const Request_Code Request::OPEN_SERVER_SIDE;
const Request_Code Request::OPEN_CLIENT_SIDE;
const Request_Code Request::KEYCODE_CTRL;
const Request_Code Request::KEYCODE_SHIFT;
const Request_Code Request::KEYCODE_ALT_LEFT;
const Request_Code Request::KEYCODE_ALT_RIGHT;
const Request_Code Request::KEYCODE_WINDOWS;
const Request_Code Request::KEYCODE_ENTER;
const Request_Code Request::KEYCODE_ESCAPE;
const Request_Code Request::KEYCODE_DELETE;
const Request_Code Request::KEYCODE_SPACE;
const Request_Code Request::KEYCODE_BACKSPACE;
const Request_Code Request::KEYCODE_TAB;
const Request_Code Request::KEYCODE_0;
const Request_Code Request::KEYCODE_1;
const Request_Code Request::KEYCODE_2;
const Request_Code Request::KEYCODE_3;
const Request_Code Request::KEYCODE_4;
const Request_Code Request::KEYCODE_5;
const Request_Code Request::KEYCODE_6;
const Request_Code Request::KEYCODE_7;
const Request_Code Request::KEYCODE_8;
const Request_Code Request::KEYCODE_9;
const Request_Code Request::KEYCODE_A;
const Request_Code Request::KEYCODE_B;
const Request_Code Request::KEYCODE_C;
const Request_Code Request::KEYCODE_D;
const Request_Code Request::KEYCODE_E;
const Request_Code Request::KEYCODE_F;
const Request_Code Request::KEYCODE_G;
const Request_Code Request::KEYCODE_H;
const Request_Code Request::KEYCODE_I;
const Request_Code Request::KEYCODE_J;
const Request_Code Request::KEYCODE_K;
const Request_Code Request::KEYCODE_L;
const Request_Code Request::KEYCODE_M;
const Request_Code Request::KEYCODE_N;
const Request_Code Request::KEYCODE_O;
const Request_Code Request::KEYCODE_P;
const Request_Code Request::KEYCODE_Q;
const Request_Code Request::KEYCODE_R;
const Request_Code Request::KEYCODE_S;
const Request_Code Request::KEYCODE_T;
const Request_Code Request::KEYCODE_U;
const Request_Code Request::KEYCODE_V;
const Request_Code Request::KEYCODE_W;
const Request_Code Request::KEYCODE_X;
const Request_Code Request::KEYCODE_Y;
const Request_Code Request::KEYCODE_Z;
const Request_Code Request::KEYCODE_F1;
const Request_Code Request::KEYCODE_F2;
const Request_Code Request::KEYCODE_F3;
const Request_Code Request::KEYCODE_F4;
const Request_Code Request::KEYCODE_F5;
const Request_Code Request::KEYCODE_F6;
const Request_Code Request::KEYCODE_F7;
const Request_Code Request::KEYCODE_F8;
const Request_Code Request::KEYCODE_F9;
const Request_Code Request::KEYCODE_F10;
const Request_Code Request::KEYCODE_F11;
const Request_Code Request::KEYCODE_F12;
const Request_Code Request::KEYCODE_EQUALS;
const Request_Code Request::KEYCODE_MINUS;
const Request_Code Request::KEYCODE_PLUS;
const Request_Code Request::KEYCODE_STAR;
const Request_Code Request::KEYCODE_SLASH;
const Request_Code Request::KEYCODE_BACKSLASH;
const Request_Code Request::KEYCODE_UNDERSCORE;
const Request_Code Request::KEYCODE_PIPE;
const Request_Code Request::KEYCODE_COMMA;
const Request_Code Request::KEYCODE_PERIODE;
const Request_Code Request::KEYCODE_COLON;
const Request_Code Request::KEYCODE_SEMICOLON;
const Request_Code Request::KEYCODE_AT;
const Request_Code Request::KEYCODE_APOSTROPHE;
const Request_Code Request::KEYCODE_LEFT_PAREN;
const Request_Code Request::KEYCODE_RIGHT_PARENT;
const Request_Code Request::KEYCODE_LEFT_BRACKET;
const Request_Code Request::KEYCODE_RIGHT_BRACKET;
const Request_Code Request::KEYCODE_LEFT_CURLY_BRACKET;
const Request_Code Request::KEYCODE_RIGHT_CURLY_BRACKET;
const Request_Code Request::KEYCODE_LEFT_ANGLE_BRACKET;
const Request_Code Request::KEYCODE_RIGHT_ANGLE_BRACKET;
const Request_Code Request::Code_MIN;
const Request_Code Request::Code_MAX;
const int Request::Code_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int Request::kTypeFieldNumber;
const int Request::kCodeFieldNumber;
const int Request::kSecurityTokenFieldNumber;
const int Request::kIntExtraFieldNumber;
const int Request::kStringExtraFieldNumber;
#endif  // !_MSC_VER

Request::Request()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:network_io.Request)
}

void Request::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Request::Request(const Request& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:network_io.Request)
}

void Request::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_ = 0;
  code_ = 0;
  securitytoken_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  intextra_ = 0;
  stringextra_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Request::~Request() {
  // @@protoc_insertion_point(destructor:network_io.Request)
  SharedDtor();
}

void Request::SharedDtor() {
  securitytoken_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  stringextra_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Request::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Request_descriptor_;
}

const Request& Request::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_remote_5fcommand_2eproto();
  return *default_instance_;
}

Request* Request::default_instance_ = NULL;

Request* Request::New(::google::protobuf::Arena* arena) const {
  Request* n = new Request;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Request::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Request*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(type_, code_);
  securitytoken_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  intextra_ = 0;
  stringextra_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef OFFSET_OF_FIELD_
#undef ZR_

}

bool Request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:network_io.Request)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .network_io.Request.Type type = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::network_io::Request_Type >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_code;
        break;
      }

      // optional .network_io.Request.Code code = 2;
      case 2: {
        if (tag == 16) {
         parse_code:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_code(static_cast< ::network_io::Request_Code >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_securityToken;
        break;
      }

      // optional string securityToken = 3;
      case 3: {
        if (tag == 26) {
         parse_securityToken:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_securitytoken()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->securitytoken().data(), this->securitytoken().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "network_io.Request.securityToken");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_intExtra;
        break;
      }

      // optional int32 intExtra = 4;
      case 4: {
        if (tag == 32) {
         parse_intExtra:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intextra_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_stringExtra;
        break;
      }

      // optional string stringExtra = 5;
      case 5: {
        if (tag == 42) {
         parse_stringExtra:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_stringextra()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->stringextra().data(), this->stringextra().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "network_io.Request.stringExtra");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:network_io.Request)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:network_io.Request)
  return false;
#undef DO_
}

void Request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:network_io.Request)
  // optional .network_io.Request.Type type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional .network_io.Request.Code code = 2;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->code(), output);
  }

  // optional string securityToken = 3;
  if (this->securitytoken().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->securitytoken().data(), this->securitytoken().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.Request.securityToken");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->securitytoken(), output);
  }

  // optional int32 intExtra = 4;
  if (this->intextra() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->intextra(), output);
  }

  // optional string stringExtra = 5;
  if (this->stringextra().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->stringextra().data(), this->stringextra().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.Request.stringExtra");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->stringextra(), output);
  }

  // @@protoc_insertion_point(serialize_end:network_io.Request)
}

::google::protobuf::uint8* Request::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:network_io.Request)
  // optional .network_io.Request.Type type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional .network_io.Request.Code code = 2;
  if (this->code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->code(), target);
  }

  // optional string securityToken = 3;
  if (this->securitytoken().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->securitytoken().data(), this->securitytoken().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.Request.securityToken");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->securitytoken(), target);
  }

  // optional int32 intExtra = 4;
  if (this->intextra() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->intextra(), target);
  }

  // optional string stringExtra = 5;
  if (this->stringextra().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->stringextra().data(), this->stringextra().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.Request.stringExtra");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->stringextra(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:network_io.Request)
  return target;
}

int Request::ByteSize() const {
  int total_size = 0;

  // optional .network_io.Request.Type type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // optional .network_io.Request.Code code = 2;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->code());
  }

  // optional string securityToken = 3;
  if (this->securitytoken().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->securitytoken());
  }

  // optional int32 intExtra = 4;
  if (this->intextra() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->intextra());
  }

  // optional string stringExtra = 5;
  if (this->stringextra().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->stringextra());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Request::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Request* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Request*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Request::MergeFrom(const Request& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
  if (from.securitytoken().size() > 0) {

    securitytoken_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.securitytoken_);
  }
  if (from.intextra() != 0) {
    set_intextra(from.intextra());
  }
  if (from.stringextra().size() > 0) {

    stringextra_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.stringextra_);
  }
}

void Request::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Request::CopyFrom(const Request& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request::IsInitialized() const {

  return true;
}

void Request::Swap(Request* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Request::InternalSwap(Request* other) {
  std::swap(type_, other->type_);
  std::swap(code_, other->code_);
  securitytoken_.Swap(&other->securitytoken_);
  std::swap(intextra_, other->intextra_);
  stringextra_.Swap(&other->stringextra_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Request::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Request_descriptor_;
  metadata.reflection = Request_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int FileInfo::kAbsoluteFilePathFieldNumber;
const int FileInfo::kFilenameFieldNumber;
const int FileInfo::kIsDirectoryFieldNumber;
const int FileInfo::kSizeFieldNumber;
const int FileInfo::kChildFieldNumber;
#endif  // !_MSC_VER

FileInfo::FileInfo()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:network_io.FileInfo)
}

void FileInfo::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  child_ = const_cast< ::network_io::FileInfo*>(&::network_io::FileInfo::default_instance());
}

FileInfo::FileInfo(const FileInfo& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:network_io.FileInfo)
}

void FileInfo::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  absolutefilepath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  filename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isdirectory_ = false;
  size_ = 0u;
  child_ = NULL;
}

FileInfo::~FileInfo() {
  // @@protoc_insertion_point(destructor:network_io.FileInfo)
  SharedDtor();
}

void FileInfo::SharedDtor() {
  absolutefilepath_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  filename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete child_;
  }
}

void FileInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FileInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FileInfo_descriptor_;
}

const FileInfo& FileInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_remote_5fcommand_2eproto();
  return *default_instance_;
}

FileInfo* FileInfo::default_instance_ = NULL;

FileInfo* FileInfo::New(::google::protobuf::Arena* arena) const {
  FileInfo* n = new FileInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FileInfo::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<FileInfo*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(isdirectory_, size_);
  absolutefilepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (child_ != NULL) delete child_;
  child_ = NULL;

#undef OFFSET_OF_FIELD_
#undef ZR_

}

bool FileInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:network_io.FileInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string absoluteFilePath = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_absolutefilepath()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->absolutefilepath().data(), this->absolutefilepath().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "network_io.FileInfo.absoluteFilePath");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_filename;
        break;
      }

      // optional string filename = 2;
      case 2: {
        if (tag == 18) {
         parse_filename:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->filename().data(), this->filename().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "network_io.FileInfo.filename");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_isDirectory;
        break;
      }

      // optional bool isDirectory = 3;
      case 3: {
        if (tag == 24) {
         parse_isDirectory:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isdirectory_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_size;
        break;
      }

      // optional uint32 size = 4;
      case 4: {
        if (tag == 32) {
         parse_size:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &size_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_child;
        break;
      }

      // optional .network_io.FileInfo child = 5;
      case 5: {
        if (tag == 42) {
         parse_child:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_child()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:network_io.FileInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:network_io.FileInfo)
  return false;
#undef DO_
}

void FileInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:network_io.FileInfo)
  // optional string absoluteFilePath = 1;
  if (this->absolutefilepath().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->absolutefilepath().data(), this->absolutefilepath().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.FileInfo.absoluteFilePath");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->absolutefilepath(), output);
  }

  // optional string filename = 2;
  if (this->filename().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->filename().data(), this->filename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.FileInfo.filename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->filename(), output);
  }

  // optional bool isDirectory = 3;
  if (this->isdirectory() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->isdirectory(), output);
  }

  // optional uint32 size = 4;
  if (this->size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->size(), output);
  }

  // optional .network_io.FileInfo child = 5;
  if (this->has_child()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *this->child_, output);
  }

  // @@protoc_insertion_point(serialize_end:network_io.FileInfo)
}

::google::protobuf::uint8* FileInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:network_io.FileInfo)
  // optional string absoluteFilePath = 1;
  if (this->absolutefilepath().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->absolutefilepath().data(), this->absolutefilepath().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.FileInfo.absoluteFilePath");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->absolutefilepath(), target);
  }

  // optional string filename = 2;
  if (this->filename().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->filename().data(), this->filename().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.FileInfo.filename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->filename(), target);
  }

  // optional bool isDirectory = 3;
  if (this->isdirectory() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->isdirectory(), target);
  }

  // optional uint32 size = 4;
  if (this->size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->size(), target);
  }

  // optional .network_io.FileInfo child = 5;
  if (this->has_child()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, *this->child_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:network_io.FileInfo)
  return target;
}

int FileInfo::ByteSize() const {
  int total_size = 0;

  // optional string absoluteFilePath = 1;
  if (this->absolutefilepath().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->absolutefilepath());
  }

  // optional string filename = 2;
  if (this->filename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->filename());
  }

  // optional bool isDirectory = 3;
  if (this->isdirectory() != 0) {
    total_size += 1 + 1;
  }

  // optional uint32 size = 4;
  if (this->size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->size());
  }

  // optional .network_io.FileInfo child = 5;
  if (this->has_child()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->child_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FileInfo::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const FileInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const FileInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FileInfo::MergeFrom(const FileInfo& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.absolutefilepath().size() > 0) {

    absolutefilepath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.absolutefilepath_);
  }
  if (from.filename().size() > 0) {

    filename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.filename_);
  }
  if (from.isdirectory() != 0) {
    set_isdirectory(from.isdirectory());
  }
  if (from.size() != 0) {
    set_size(from.size());
  }
  if (from.has_child()) {
    mutable_child()->::network_io::FileInfo::MergeFrom(from.child());
  }
}

void FileInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FileInfo::CopyFrom(const FileInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileInfo::IsInitialized() const {

  return true;
}

void FileInfo::Swap(FileInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FileInfo::InternalSwap(FileInfo* other) {
  absolutefilepath_.Swap(&other->absolutefilepath_);
  filename_.Swap(&other->filename_);
  std::swap(isdirectory_, other->isdirectory_);
  std::swap(size_, other->size_);
  std::swap(child_, other->child_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FileInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FileInfo_descriptor_;
  metadata.reflection = FileInfo_reflection_;
  return metadata;
}


// ===================================================================

const ::google::protobuf::EnumDescriptor* Response_ReturnCode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Response_ReturnCode_descriptor_;
}
bool Response_ReturnCode_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Response_ReturnCode Response::RC_SUCCESS;
const Response_ReturnCode Response::RC_ERROR;
const Response_ReturnCode Response::ReturnCode_MIN;
const Response_ReturnCode Response::ReturnCode_MAX;
const int Response::ReturnCode_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int Response::kRequestTypeFieldNumber;
const int Response::kRequestCodeFieldNumber;
const int Response::kReturnCodeFieldNumber;
const int Response::kMessageFieldNumber;
const int Response::kIntValueFieldNumber;
const int Response::kFileFieldNumber;
#endif  // !_MSC_VER

Response::Response()
  : ::google::protobuf::Message() , _internal_metadata_(NULL)  {
  SharedCtor();
  // @@protoc_insertion_point(constructor:network_io.Response)
}

void Response::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  file_ = const_cast< ::network_io::FileInfo*>(&::network_io::FileInfo::default_instance());
}

Response::Response(const Response& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:network_io.Response)
}

void Response::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  requesttype_ = 0;
  requestcode_ = 0;
  returncode_ = 0;
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  intvalue_ = 0;
  file_ = NULL;
}

Response::~Response() {
  // @@protoc_insertion_point(destructor:network_io.Response)
  SharedDtor();
}

void Response::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
    delete file_;
  }
}

void Response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Response::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Response_descriptor_;
}

const Response& Response::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_remote_5fcommand_2eproto();
  return *default_instance_;
}

Response* Response::default_instance_ = NULL;

Response* Response::New(::google::protobuf::Arena* arena) const {
  Response* n = new Response;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Response::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Response*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(requesttype_, requestcode_);
  ZR_(returncode_, intvalue_);
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (file_ != NULL) delete file_;
  file_ = NULL;

#undef OFFSET_OF_FIELD_
#undef ZR_

}

bool Response::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:network_io.Response)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .network_io.Request.Type requestType = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_requesttype(static_cast< ::network_io::Request_Type >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_requestCode;
        break;
      }

      // optional .network_io.Request.Code requestCode = 2;
      case 2: {
        if (tag == 16) {
         parse_requestCode:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_requestcode(static_cast< ::network_io::Request_Code >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_returnCode;
        break;
      }

      // optional .network_io.Response.ReturnCode returnCode = 3;
      case 3: {
        if (tag == 24) {
         parse_returnCode:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_returncode(static_cast< ::network_io::Response_ReturnCode >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_message;
        break;
      }

      // optional string message = 4;
      case 4: {
        if (tag == 34) {
         parse_message:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "network_io.Response.message");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_intValue;
        break;
      }

      // optional int32 intValue = 5;
      case 5: {
        if (tag == 40) {
         parse_intValue:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intvalue_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_file;
        break;
      }

      // optional .network_io.FileInfo file = 6;
      case 6: {
        if (tag == 50) {
         parse_file:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_file()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:network_io.Response)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:network_io.Response)
  return false;
#undef DO_
}

void Response::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:network_io.Response)
  // optional .network_io.Request.Type requestType = 1;
  if (this->requesttype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->requesttype(), output);
  }

  // optional .network_io.Request.Code requestCode = 2;
  if (this->requestcode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->requestcode(), output);
  }

  // optional .network_io.Response.ReturnCode returnCode = 3;
  if (this->returncode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->returncode(), output);
  }

  // optional string message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.Response.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->message(), output);
  }

  // optional int32 intValue = 5;
  if (this->intvalue() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->intvalue(), output);
  }

  // optional .network_io.FileInfo file = 6;
  if (this->has_file()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, *this->file_, output);
  }

  // @@protoc_insertion_point(serialize_end:network_io.Response)
}

::google::protobuf::uint8* Response::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:network_io.Response)
  // optional .network_io.Request.Type requestType = 1;
  if (this->requesttype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->requesttype(), target);
  }

  // optional .network_io.Request.Code requestCode = 2;
  if (this->requestcode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->requestcode(), target);
  }

  // optional .network_io.Response.ReturnCode returnCode = 3;
  if (this->returncode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->returncode(), target);
  }

  // optional string message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "network_io.Response.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->message(), target);
  }

  // optional int32 intValue = 5;
  if (this->intvalue() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->intvalue(), target);
  }

  // optional .network_io.FileInfo file = 6;
  if (this->has_file()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, *this->file_, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:network_io.Response)
  return target;
}

int Response::ByteSize() const {
  int total_size = 0;

  // optional .network_io.Request.Type requestType = 1;
  if (this->requesttype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->requesttype());
  }

  // optional .network_io.Request.Code requestCode = 2;
  if (this->requestcode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->requestcode());
  }

  // optional .network_io.Response.ReturnCode returnCode = 3;
  if (this->returncode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->returncode());
  }

  // optional string message = 4;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // optional int32 intValue = 5;
  if (this->intvalue() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->intvalue());
  }

  // optional .network_io.FileInfo file = 6;
  if (this->has_file()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->file_);
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Response::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Response* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Response*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Response::MergeFrom(const Response& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.requesttype() != 0) {
    set_requesttype(from.requesttype());
  }
  if (from.requestcode() != 0) {
    set_requestcode(from.requestcode());
  }
  if (from.returncode() != 0) {
    set_returncode(from.returncode());
  }
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.intvalue() != 0) {
    set_intvalue(from.intvalue());
  }
  if (from.has_file()) {
    mutable_file()->::network_io::FileInfo::MergeFrom(from.file());
  }
}

void Response::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Response::CopyFrom(const Response& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response::IsInitialized() const {

  return true;
}

void Response::Swap(Response* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Response::InternalSwap(Response* other) {
  std::swap(requesttype_, other->requesttype_);
  std::swap(requestcode_, other->requestcode_);
  std::swap(returncode_, other->returncode_);
  message_.Swap(&other->message_);
  std::swap(intvalue_, other->intvalue_);
  std::swap(file_, other->file_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Response::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Response_descriptor_;
  metadata.reflection = Response_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace network_io

// @@protoc_insertion_point(global_scope)
